### ISSUE TITLE
Looking for new maintainer

### ISSUE THREAD

**Issue by roryrjb** [Richienb/iplocation#24]
I don't use this module anymore, and to be honest I don't even use Node.js or GitHub much anymore, and I don't have the time to update it, review issues or pull requests, so I am looking for a new maintainer. I won't just pick anyone, as people are using the module, so I have to ensure it goes into good hands, it's not complicated and there isn't much coding involved it's more about checking providers and keeping on top of stuff. If no one suitable comes forward (in a reasonable amount of time) I will deprecate the module in npm and archive the repo in GitHub.

**Comment by madc0de** [comment]
Hi, will to maintain the project and like to do some changes, since IP information providers usually has limits.

**Comment by roryrjb** [comment]
@madc0de thanks for your interest in the project. Perhaps you could submit at least one PR, as a first step and then we can see about changing ownership of the project.

**Comment by Richienb** [comment]
@roryrjb Hi, I can continue maintaining this project. I'll send in a few PRs...

**Comment by roryrjb** [comment]
@Richienb thank you. I am happy to transfer ownership, but as you have a repo already called `iplocation` I can't do it, (due to your fork there). I have now merged your PR (thanks again!), let me know when you've renamed/deleted your fork and I will move it over. I will also give you NPM access just now.

**Comment by roryrjb** [comment]
@Richienb ok done. Also added you as a maintainer on NPM. Thanks again!

**Comment by Richienb** [comment]
@roryrjb I could also take over https://www.npmjs.com/package/iplocation-cli if need be.

**Comment by roryrjb** [comment]
@Richienb ok done, although the git repo is already gone, but you can restore it from the NPM package itself.
